---
- name: install tomcat 10
  hosts: appservers
  become: yes
  tasks:
    - name: update packages and install java
      ansible.builtin.apt:
        name: openjdk-17-jdk
        update_cache: yes
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        home: /opt/tomcat
        shell: /bin/false
        state: present
    