---
- name: installing tomcat 10
  become: yes
  hosts: appservers
  tasks:
    - name: install openjdk with "{{ java_package_name }}"
      ansible.builtin.apt:
        name: "{{ java_package_name }}"
        update_cache: yes
        state: present
    - name: create a user tomcat
      ansible.builtin.user:
        name: "{{ user_name }}"
        create_home: yes
        home: "{{ user_home }}"
        shell: "{{ user_shell }}"
        state: present
    - name: extracting tomcat
      ansible.builtin.unarchive:
        src: "{{ download_url }}"
        dest: "{{ user_home }}"
        remote_src: yes
        extra_opts: [ --strip-components=1 ]
    - name: recursive change ownership to tomcat
      ansible.builtin.file:
        path: "{{ user_home }}"
        state: directory
        recurse: yes
        owner: "{{ user_name }}"
        group: "{{ user_name }}"