---
- name: install tomcat 10
  hosts: appservers
  become: yes
  tasks:
    - name: update packages and install java
      ansible.builtin.apt:
        name: openjdk-17-jdk
        update_cache: yes
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        home: /opt/tomcat
        shell: /bin/false
        state: present
    - name: download and extract tomcat
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.43/bin/apache-tomcat-10.1.43.tar.gz
        dest: /opt/tomcat
        remote_src: yes
    