---
- name: Learning conditionals
  hosts: all
  tasks:
    - name: run this only on debian
      ansible.builtin.debug:
        msg: "This is debian based os"
      when: ansible_facts['os_family'] == "Debian"
    - name: run this only on redhat
      ansible.builtin.debug:
        msg: "This is Redhat based os"
      when: ansible_facts['os_family'] == "RedHat"
    - name: run this on 'Ubuntu' distribution less than 22
      ansible.builtin.debug:
        msg: "This is older Ubuntu"
      when:
        - ansible_facts['distribution'] == 'Ubuntu'
        - ansible_facts['distribution_version'] | int <= 22

    