---
- name: Learning conditionals
  hosts: all
  tasks:
    - name: run this only on debian
      ansible.builtin.debug:
        msg: "This is debian based os"
      when: ansible_facts['os_family'] == "Debian"
    - name: run this only on redhat
      ansible.builtin.debug:
        msg: "This is Redhat based os"
      when: ansible_facts['os_family'] == "RedHat"
    - name: run this on 'Ubuntu' distribution less than 22
      ansible.builtin.debug:
        msg: "This is older Ubuntu"
      when:
        - ansible_facts['distribution'] == 'Ubuntu'
        - ansible_facts['distribution_version'] | int <= 22
    - name: register info in a variable
      ansible.builtin.stat:
        path: /home/devops/test.txt
      register: file_status
    - name: print the contents of the variable
      ansible.builtin.debug:
        var: file_status
    - name: Run this if a file exists
      ansible.builtin.debug:
        msg: file exists at /home/devops/test.txt
      when: file_status.stat.exists
    - name: Display paths of /home/devops/test.txt in dir
      ansible.builtin.debug: msg={{ lookup('ansible.builtin.fileglob', '/home/devops/test.txt') }}


    