---
- name: update packages
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"
- name: install java
  ansible.builtin.package:
    name: "{{ java_package_name }}"
    state: present
