---
- name: install tomcat 10
  hosts: appserver
  become: yes
  tasks:
    - name: fail if it is not ubuntu
      ansible.builtin.fail:
        msg: This playbook is for Ubuntu only
      when:  ansible_facts['distribution'] != "Ubuntu"
    - name: install java
      ansible.builtin.apt:
        name: "{{ java_package_name }}"
        update_cache: yes
        state: present
    - name: create a tomcat group
      ansible.builtin.group:
        name: "{{ tomcat_group }}"
        state: present
    - name: create a tomcat group
      ansible.builtin.user:
        name: "{{ tomcat_user }}"
        create_home: yes
        group: "{{ tomcat_group }}"
        home: "{{ tomcat_home_dir }}"
        shell: "{{ tomcat_shell }}"
    - name: download and extract tomcat
      ansible.builtin.unarchive:
        src: "{{ tomcat_download_url }}"
        dest: "{{ tomcat_home_dir }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        remote_src: yes
        extra_opts:
          - --strip-components=1
    - name: copy tomcat-users file
      ansible.builtin.template:
        src: templates/tomcat-users.xml.j2
        dest: "{{ tomcat_home_dir }}/conf/tomcat-users.xml"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0600'
    - name: copy manager context file
      ansible.builtin.template:
        src: templates/context.xml.j2
        dest: "{{ tomcat_home_dir }}/webapps/manager/META-INF/context.xml"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0600'
    - name: copy host-manager context file
      ansible.builtin.template:
        src: templates/context.xml.j2
        dest: "{{ tomcat_home_dir }}/webapps/host-manager/META-INF/context.xml"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0600'
    